#qsub -cwd -b y -j y -V "/share/ClusterShare/software/contrib/briglo/octR/src/R-3.6.0/builddir/bin/R CMD BATCH /share/ScratchGeneral/jamtor/projects/single_cell/identify_epithelial/scripts/install_inferCNV.R"

library(devtools)
install.packages("tidyr", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("reshape", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("gtools", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("dplyr", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("tidyselect", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("purrr", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("tidyselect", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("dplyr", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("glue", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("dplyr", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("coin", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("zoo", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("coin", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("libcoin", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("coin", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("caTools", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("tibble", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("rlang", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("digest", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("lsei", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
install.packages("Matrix", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
BiocManager::install("edgeR", lib="/share/ScratchGeneral/jamtor/R/3.6.0/")
install.packages("jsonlite", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", repos="https://cran.csiro.au/")
system("export PKG_CONFIG_PATH=/share/ScratchGeneral/jamtor/local/lib/JAGS-4.3.0/etc")
install.packages("rjags", lib="/share/ScratchGeneral/jamtor/R/3.6.0/", configure.args="--enable-rpath", repos="https://cran.csiro.au/")
BiocManager::install("infercnv", lib="/share/ScratchGeneral/jamtor/R/3.6.0/")
